# This is a basic workflow to help you get started with Actions

name: Automate Tweet
on:
  schedule:
    - cron: '*/5  * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Scheduling
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
     - name: Ping URL (JavaScript action)
  # You may pin to the exact commit or the version.
  # uses: soul-wish/ping-url-javascript-action@a859fd903f27430ca566fbe94da9ce2c5e0c04d9
       uses: soul-wish/ping-url-javascript-action@v1.2
       with:
        # URL to ping
        url: https://github.com/
